### ISSUE TITLE
Broken Smartcar::User.user_id method #1

### ISSUE THREAD

**Issue by s-ashwinkumar** [smartcar/ruby-sdk#14]
Issue copied from https://github.com/vickodin/ruby-sdk/issues/1

Some troubles:

In case of no data parameter here, there will be an error (try use nil as a a hash), but we don't have any hash as params here (USER_PATH only).

There is a required instance's method (unit_system) here, that is missing in the User.

Also, any method (get, post, etc) returns an array with two elements: body and meta here, but we use a hash here (['id']).

As result, we can't invoke user_id method without raise errors.

**Comment by vickodin** [comment]
Also, you use module Utils - https://github.com/smartcar/ruby-sdk/blob/master/lib/smartcar/utils.rb
without Smartcar module (it isn't nested inside Smartcar module). 

We have conflict with namespaces in this case (we also have Utils in our app).

Thanks!

**Comment by s-ashwinkumar** [comment]
This issue has been resolved in the latest release [v2.2.0](https://github.com/smartcar/ruby-sdk/releases/tag/v2.2.0). @vickodin  thank you for reporting these.
